/**
 ******************************************************************************
 * @file      startup_STM32U385RGTxQ.s
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32U385RGTxQ device vector table for GCC toolchain.
 *            This module performs:
 *                - Set the initial SP
 *                - Set the initial PC == Reset_Handler,
 *                - Set the vector table entries with the exceptions ISR address
 *                - Branches to main in the C library (which eventually
 *                  calls main()).
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

.syntax unified
.cpu cortex-m33
.fpu softvfp
.thumb

.global g_pfnVectors
.global Default_Handler

/* start address for the initialization values of the .data section.
defined in linker script */
.word _sidata
/* start address for the .data section. defined in linker script */
.word _sdata
/* end address for the .data section. defined in linker script */
.word _edata
/* start address for the .bss section. defined in linker script */
.word _sbss
/* end address for the .bss section. defined in linker script */
.word _ebss

/**
 * @brief  This is the code that gets called when the processor first
 *          starts execution following a reset event. Only the absolutely
 *          necessary set is performed, after which the application
 *          supplied main() routine is called.
 * @param  None
 * @retval : None
*/

  .section .text.Reset_Handler
  .weak Reset_Handler
  .type Reset_Handler, %function
Reset_Handler:
  ldr   r0, =_estack
  mov   sp, r0          /* set stack pointer */
/* Call the clock system initialization function.*/
  bl  SystemInit

/* Copy the data segment initializers from flash to SRAM */
  ldr r0, =_sdata
  ldr r1, =_edata
  ldr r2, =_sidata
  movs r3, #0
  b LoopCopyDataInit

CopyDataInit:
  ldr r4, [r2, r3]
  str r4, [r0, r3]
  adds r3, r3, #4

LoopCopyDataInit:
  adds r4, r0, r3
  cmp r4, r1
  bcc CopyDataInit

/* Zero fill the bss segment. */
  ldr r2, =_sbss
  ldr r4, =_ebss
  movs r3, #0
  b LoopFillZerobss

FillZerobss:
  str  r3, [r2]
  adds r2, r2, #4

LoopFillZerobss:
  cmp r2, r4
  bcc FillZerobss

/* Call static constructors */
  bl __libc_init_array
/* Call the application's entry point.*/
  bl main

LoopForever:
  b LoopForever

  .size Reset_Handler, .-Reset_Handler

/**
 * @brief  This is the code that gets called when the processor receives an
 *         unexpected interrupt.  This simply enters an infinite loop, preserving
 *         the system state for examination by a debugger.
 *
 * @param  None
 * @retval : None
*/
  .section .text.Default_Handler,"ax",%progbits
Default_Handler:
Infinite_Loop:
  b Infinite_Loop
  .size Default_Handler, .-Default_Handler

/******************************************************************************
*
* The STM32U385RGTxQ vector table.  Note that the proper constructs
* must be placed on this to ensure that it ends up at physical address
* 0x0000.0000.
*
******************************************************************************/
  .section .isr_vector,"a",%progbits
  .type g_pfnVectors, %object
  .size g_pfnVectors, .-g_pfnVectors

g_pfnVectors:
  .word _estack
  .word Reset_Handler
  .word NMI_Handler
  .word HardFault_Handler
  .word	MemManage_Handler
  .word	BusFault_Handler
  .word	UsageFault_Handler
  .word	SecureFault_Handler
  .word	0
  .word	0
  .word	0
  .word	SVC_Handler
  .word	DebugMon_Handler
  .word	0
  .word	PendSV_Handler
  .word	SysTick_Handler
  .word	WWDG_IRQHandler            			/* Window Watchdog interrupt                                                     */
  .word	PVD_PVM_IRQHandler         			/* Programmable voltage detector/peripheral voltage monitor - EXTI16/19/20/21/22 */
  .word	RTC_IRQHandler             			/* RTC global non-secure interrupts                                              */
  .word	RTC_S_IRQHandler           			/* RTC global secure interrupts                                                  */
  .word	TAMP_IRQHandler            			/* Tamper global interrupts                                                      */
  .word	RAMCFG_IRQHandler          			/* RAM configuration global interrupt                                            */
  .word	FLASH_IRQHandler           			/* Flash memory non-secure global interrupt                                      */
  .word	FLASH_S_IRQHandler         			/* Flash memory secure global interrupt                                          */
  .word	GTZC_IRQHandler            			/* GTZC1/GTZC2 global interrupt                                                  */
  .word	RCC_IRQHandler             			/* RCC non-secure global interrupt                                               */
  .word	RCC_S_IRQHandler           			/* RCC secure global interrupt                                                   */
  .word	EXTI0_IRQHandler           			/* EXTI line0 interrupt                                                          */
  .word	EXTI1_IRQHandler           			/* EXTI line1 interrupt                                                          */
  .word	EXTI2_IRQHandler           			/* EXTI line2 interrupt                                                          */
  .word	EXTI3_IRQHandler           			/* EXTI line3 interrupt                                                          */
  .word	EXTI4_IRQHandler           			/* EXTI line4 interrupt                                                          */
  .word	EXTI5_IRQHandler           			/* EXTI line5 interrupt                                                          */
  .word	EXTI6_IRQHandler           			/* EXTI line6 interrupt                                                          */
  .word	EXTI7_IRQHandler           			/* EXTI line7 interrupt                                                          */
  .word	EXTI8_IRQHandler           			/* EXTI line8 interrupt                                                          */
  .word	EXTI9_IRQHandler           			/* EXTI line9 interrupt                                                          */
  .word	EXTI10_IRQHandler          			/* EXTI line10 interrupt                                                         */
  .word	EXTI11_IRQHandler          			/* EXTI line11 interrupt                                                         */
  .word	EXTI12_IRQHandler          			/* EXTI line12 interrupt                                                         */
  .word	EXTI13_IRQHandler          			/* EXTI line13 interrupt                                                         */
  .word	EXTI14_IRQHandler          			/* EXTI line14 interrupt                                                         */
  .word	EXTI15_IRQHandler          			/* EXTI line15 interrupt                                                         */
  .word	IWDG_IRQHandler            			/* Independent watchdog interrupt                                                */
  .word	SAES_IRQHandler            			/* Secure AES                                                                    */
  .word	GPDMA1_CHannel0_IRQHandler 			/* GPDMA1 channel 0 global interrupt                                             */
  .word	GPDMA1_CHannel1_IRQHandler 			/* GPDMA1 channel 1 global interrupt                                             */
  .word	GPDMA1_CHannel2_IRQHandler 			/* GPDMA1 channel 2 global interrupt                                             */
  .word	GPDMA1_CHannel3_IRQHandler 			/* GPDMA1 channel 3 global interrupt                                             */
  .word	GPDMA1_CHannel4_IRQHandler 			/* GPDMA1 channel 4 global interrupt                                             */
  .word	GPDMA1_CHannel5_IRQHandler 			/* GPDMA1 channel 5 global interrupt                                             */
  .word	GPDMA1_CHannel6_IRQHandler 			/* GPDMA1 channel 6 global interrupt                                             */
  .word	GPDMA1_CHannel7_IRQHandler 			/* GPDMA1 channel 7 global interrupt                                             */
  .word	ADC1_IRQHandler            			/* ADC1 global interrupt                                                         */
  .word	DAC1_IRQHandler            			/* DAC1 global interrupt                                                         */
  .word	FDCAN1_IT0_IRQHandler      			/* FDCAN Interrupt 0                                                            */
  .word	FDCAN1_IT1_IRQHandler      			/* FDCAN Interrupt 1                                                            */
  .word	TIM1_BRK_IRQHandler        			/* TIM1 Break - transition error -index error                                    */
  .word	TIM1_UP_IRQHandler         			/* TIM1 Update                                                                   */
  .word	TIM1_TRG_COM_IRQHandler    			/* TIM1 Trigger and Commutation - direction change interrupt -index              */
  .word	TIM1_CC_IRQHandler         			/* TIM1 Capture Compare interrupt                                                */
  .word	TIM2_IRQHandler            			/* TIM2 global interrupt                                                         */
  .word	TIM3_IRQHandler            			/* TIM3 global interrupt                                                         */
  .word	TIM4_IRQHandler            			/* TIM4 global interrupt                                                         */
  .word	0                          			/* Reserved                                                                      */
  .word	TIM6_IRQHandler            			/* TIM6 global interrupt                                                         */
  .word	TIM7_IRQHandler            			/* TIM7 global interrupt                                                         */
  .word	0                          			/* Reserved                                                                      */
  .word	0                          			/* Reserved                                                                      */
  .word	I3C1_ER_IRQHandler         			/* I3C1 error interrupt                                                          */
  .word	I3C1_EV_IRQHandler         			/* I3C1 event interrupt                                                          */
  .word	I2C1_EV_IRQHandler         			/* I2C1 event interrupt                                                          */
  .word	I2C1_ER_IRQHandler         			/* I2C1 error interrupt                                                          */
  .word	I2C2_EV_IRQHandler         			/* I2C2 event interrupt                                                          */
  .word	I2C2_ER_IRQHandler         			/* I2C2 error interrupt                                                          */
  .word	SPI1_IRQHandler            			/* SPI1 global interrupt                                                         */
  .word	SPI2_IRQHandler            			/* SPI2 global interrupt                                                         */
  .word	USART1_IRQHandler          			/* USART1 global interrupt                                                       */
  .word	0                          			/* Reserved                                                                      */
  .word	USART3_IRQHandler          			/* USART3 global interrupt                                                       */
  .word	USART4_IRQHandler          			/* USART4 global interrupt                                                       */
  .word	USART5_IRQHandler          			/* USART5 global interrupt                                                       */
  .word	LPUART1_IRQHandler         			/* LPUART1 global interrupt                                                      */
  .word	LPTIM1_IRQHandler          			/* LPTIM1 global interrupt                                                       */
  .word	LPTIM2_IRQHandler          			/* LPTIM2 global interrupt                                                       */
  .word	TIM15_IRQHandler           			/* TIM15 global interrupt                                                        */
  .word	TIM16_IRQHandler           			/* TIM16 global interrupt                                                        */
  .word	TIM17_IRQHandler           			/* TIM17 global interrupt                                                        */
  .word	COMP_IRQHandler            			/* COMP1/COMP2                                                                   */
  .word	USB_FS_IRQHandler          			/* USB FS global interrupt                                                       */
  .word	CRS_IRQHandler             			/* Clock recovery system global interrupt                                        */
  .word	0                          			/* Reserved                                                                      */
  .word	OCTOSPI1_IRQHandler        			/* OCTOSPI1 global interrupt                                                     */
  .word	0                          			/* Reserved                                                                      */
  .word	SDMMC1_IRQHandler          			/* SDMMC1 global interrupt                                                       */
  .word	0                          			/* Reserved                                                                      */
  .word	GPDMA1_CHannel8_IRQHandler 			/* GPDMA1 channel 8 global interrupt                                             */
  .word	GPDMA1_CHannel9_IRQHandler 			/* GPDMA1 channel 9 global interrupt                                             */
  .word	GPDMA1_CHannel10_IRQHandler			/* GPDMA1 channel 10 global interrupt                                            */
  .word	GPDMA1_CHannel11_IRQHandler			/* GPDMA1 channel 11 global interrupt                                            */
  .word	0                          			/* Reserved                                                                      */
  .word	0                          			/* Reserved                                                                      */
  .word	0                          			/* Reserved                                                                      */
  .word	0                          			/* Reserved                                                                      */
  .word	I2C3_EV_IRQHandler         			/* I2C3 event interrupt                                                          */
  .word	I2C3_ER_IRQHandler         			/* I2C3 error interrupt                                                          */
  .word	SAI1_IRQHandler            			/* SAI1 global interrupt                                                         */
  .word	0                          			/* Reserved                                                                      */
  .word	TSC_IRQHandler             			/* TSC global interrupt                                                          */
  .word	AES_IRQHandler             			/* AES global interrupt                                                          */
  .word	RNG_IRQHandler             			/* RNG global interrupt                                                          */
  .word	FPU_IRQHandler             			/* Floating point interrupt                                                      */
  .word	HASH_IRQHandler            			/* HASH interrupt                                                                */
  .word	PKA_IRQHandler             			/* PKA global interrupt                                                          */
  .word	LPTIM3_IRQHandler          			/* LPTIM3 global interrupt                                                       */
  .word	SPI3_IRQHandler            			/* SPI3 global interrupt                                                         */
  .word	I3C2_ER_IRQHandler         			/* I3C2 error interrupt                                                          */
  .word	I3C2_EV_IRQHandler         			/* I3C2 event interrupt                                                          */
  .word	0                          			/* Reserved                                                                      */
  .word	0                          			/* Reserved                                                                      */
  .word	0                          			/* Reserved                                                                      */
  .word	0                          			/* Reserved                                                                      */
  .word	0                          			/* Reserved                                                                      */
  .word	ICACHE_IRQHandler          			/* Instruction cache global interrupt                                            */
  .word	0                          			/* Reserved                                                                      */
  .word	0                          			/* Reserved                                                                      */
  .word	LPTIM4_IRQHandler          			/* LPTIM4 global interrupt                                                       */
  .word	0                          			/* Reserved                                                                      */
  .word	ADF1_IRQHandler            			/* ADF1 interrupt                                                                */
  .word	ADC2_IRQHandler            			/* ADC2 global interrupt                                                         */
  .word	0                          			/* Reserved                                                                      */
  .word	0                          			/* Reserved                                                                      */
  .word	0                          			/* Reserved                                                                      */
  .word	0                          			/* Reserved                                                                      */
  .word	0                          			/* Reserved                                                                      */
  .word	0                          			/* Reserved                                                                      */
  .word	0                          			/* Reserved                                                                      */
  .word	0                          			/* Reserved                                                                      */
  .word	0                          			/* Reserved                                                                      */
  .word	PWR_IRQHandler             			/* PWR non-secure interrupt                                                      */
  .word	PWR_S_IRQHandler           			/* PWR secure interrupt                                                          */

/*******************************************************************************
*
* Provide weak aliases for each Exception handler to the Default_Handler.
* As they are weak aliases, any function with the same name will override
* this definition.
*
*******************************************************************************/

	.weak	NMI_Handler
	.thumb_set NMI_Handler,Default_Handler

	.weak	HardFault_Handler
	.thumb_set HardFault_Handler,Default_Handler

	.weak	MemManage_Handler
	.thumb_set MemManage_Handler,Default_Handler

	.weak	BusFault_Handler
	.thumb_set BusFault_Handler,Default_Handler

	.weak	UsageFault_Handler
	.thumb_set UsageFault_Handler,Default_Handler

	.weak	SecureFault_Handler
	.thumb_set SecureFault_Handler,Default_Handler

	.weak	SVC_Handler
	.thumb_set SVC_Handler,Default_Handler

	.weak	DebugMon_Handler
	.thumb_set DebugMon_Handler,Default_Handler

	.weak	PendSV_Handler
	.thumb_set PendSV_Handler,Default_Handler

	.weak	SysTick_Handler
	.thumb_set SysTick_Handler,Default_Handler

	.weak	WWDG_IRQHandler
	.thumb_set WWDG_IRQHandler,Default_Handler

	.weak	PVD_PVM_IRQHandler
	.thumb_set PVD_PVM_IRQHandler,Default_Handler

	.weak	RTC_IRQHandler
	.thumb_set RTC_IRQHandler,Default_Handler

	.weak	RTC_S_IRQHandler
	.thumb_set RTC_S_IRQHandler,Default_Handler

	.weak	TAMP_IRQHandler
	.thumb_set TAMP_IRQHandler,Default_Handler

	.weak	RAMCFG_IRQHandler
	.thumb_set RAMCFG_IRQHandler,Default_Handler

	.weak	FLASH_IRQHandler
	.thumb_set FLASH_IRQHandler,Default_Handler

	.weak	FLASH_S_IRQHandler
	.thumb_set FLASH_S_IRQHandler,Default_Handler

	.weak	GTZC_IRQHandler
	.thumb_set GTZC_IRQHandler,Default_Handler

	.weak	RCC_IRQHandler
	.thumb_set RCC_IRQHandler,Default_Handler

	.weak	RCC_S_IRQHandler
	.thumb_set RCC_S_IRQHandler,Default_Handler

	.weak	EXTI0_IRQHandler
	.thumb_set EXTI0_IRQHandler,Default_Handler

	.weak	EXTI1_IRQHandler
	.thumb_set EXTI1_IRQHandler,Default_Handler

	.weak	EXTI2_IRQHandler
	.thumb_set EXTI2_IRQHandler,Default_Handler

	.weak	EXTI3_IRQHandler
	.thumb_set EXTI3_IRQHandler,Default_Handler

	.weak	EXTI4_IRQHandler
	.thumb_set EXTI4_IRQHandler,Default_Handler

	.weak	EXTI5_IRQHandler
	.thumb_set EXTI5_IRQHandler,Default_Handler

	.weak	EXTI6_IRQHandler
	.thumb_set EXTI6_IRQHandler,Default_Handler

	.weak	EXTI7_IRQHandler
	.thumb_set EXTI7_IRQHandler,Default_Handler

	.weak	EXTI8_IRQHandler
	.thumb_set EXTI8_IRQHandler,Default_Handler

	.weak	EXTI9_IRQHandler
	.thumb_set EXTI9_IRQHandler,Default_Handler

	.weak	EXTI10_IRQHandler
	.thumb_set EXTI10_IRQHandler,Default_Handler

	.weak	EXTI11_IRQHandler
	.thumb_set EXTI11_IRQHandler,Default_Handler

	.weak	EXTI12_IRQHandler
	.thumb_set EXTI12_IRQHandler,Default_Handler

	.weak	EXTI13_IRQHandler
	.thumb_set EXTI13_IRQHandler,Default_Handler

	.weak	EXTI14_IRQHandler
	.thumb_set EXTI14_IRQHandler,Default_Handler

	.weak	EXTI15_IRQHandler
	.thumb_set EXTI15_IRQHandler,Default_Handler

	.weak	IWDG_IRQHandler
	.thumb_set IWDG_IRQHandler,Default_Handler

	.weak	SAES_IRQHandler
	.thumb_set SAES_IRQHandler,Default_Handler

	.weak	GPDMA1_CHannel0_IRQHandler
	.thumb_set GPDMA1_CHannel0_IRQHandler,Default_Handler

	.weak	GPDMA1_CHannel1_IRQHandler
	.thumb_set GPDMA1_CHannel1_IRQHandler,Default_Handler

	.weak	GPDMA1_CHannel2_IRQHandler
	.thumb_set GPDMA1_CHannel2_IRQHandler,Default_Handler

	.weak	GPDMA1_CHannel3_IRQHandler
	.thumb_set GPDMA1_CHannel3_IRQHandler,Default_Handler

	.weak	GPDMA1_CHannel4_IRQHandler
	.thumb_set GPDMA1_CHannel4_IRQHandler,Default_Handler

	.weak	GPDMA1_CHannel5_IRQHandler
	.thumb_set GPDMA1_CHannel5_IRQHandler,Default_Handler

	.weak	GPDMA1_CHannel6_IRQHandler
	.thumb_set GPDMA1_CHannel6_IRQHandler,Default_Handler

	.weak	GPDMA1_CHannel7_IRQHandler
	.thumb_set GPDMA1_CHannel7_IRQHandler,Default_Handler

	.weak	ADC1_IRQHandler
	.thumb_set ADC1_IRQHandler,Default_Handler

	.weak	DAC1_IRQHandler
	.thumb_set DAC1_IRQHandler,Default_Handler

	.weak	FDCAN1_IT0_IRQHandler
	.thumb_set FDCAN1_IT0_IRQHandler,Default_Handler

	.weak	FDCAN1_IT1_IRQHandler
	.thumb_set FDCAN1_IT1_IRQHandler,Default_Handler

	.weak	TIM1_BRK_IRQHandler
	.thumb_set TIM1_BRK_IRQHandler,Default_Handler

	.weak	TIM1_UP_IRQHandler
	.thumb_set TIM1_UP_IRQHandler,Default_Handler

	.weak	TIM1_TRG_COM_IRQHandler
	.thumb_set TIM1_TRG_COM_IRQHandler,Default_Handler

	.weak	TIM1_CC_IRQHandler
	.thumb_set TIM1_CC_IRQHandler,Default_Handler

	.weak	TIM2_IRQHandler
	.thumb_set TIM2_IRQHandler,Default_Handler

	.weak	TIM3_IRQHandler
	.thumb_set TIM3_IRQHandler,Default_Handler

	.weak	TIM4_IRQHandler
	.thumb_set TIM4_IRQHandler,Default_Handler

	.weak	TIM6_IRQHandler
	.thumb_set TIM6_IRQHandler,Default_Handler

	.weak	TIM7_IRQHandler
	.thumb_set TIM7_IRQHandler,Default_Handler

	.weak	I3C1_ER_IRQHandler
	.thumb_set I3C1_ER_IRQHandler,Default_Handler

	.weak	I3C1_EV_IRQHandler
	.thumb_set I3C1_EV_IRQHandler,Default_Handler

	.weak	I2C1_EV_IRQHandler
	.thumb_set I2C1_EV_IRQHandler,Default_Handler

	.weak	I2C1_ER_IRQHandler
	.thumb_set I2C1_ER_IRQHandler,Default_Handler

	.weak	I2C2_EV_IRQHandler
	.thumb_set I2C2_EV_IRQHandler,Default_Handler

	.weak	I2C2_ER_IRQHandler
	.thumb_set I2C2_ER_IRQHandler,Default_Handler

	.weak	SPI1_IRQHandler
	.thumb_set SPI1_IRQHandler,Default_Handler

	.weak	SPI2_IRQHandler
	.thumb_set SPI2_IRQHandler,Default_Handler

	.weak	USART1_IRQHandler
	.thumb_set USART1_IRQHandler,Default_Handler

	.weak	USART3_IRQHandler
	.thumb_set USART3_IRQHandler,Default_Handler

	.weak	USART4_IRQHandler
	.thumb_set USART4_IRQHandler,Default_Handler

	.weak	USART5_IRQHandler
	.thumb_set USART5_IRQHandler,Default_Handler

	.weak	LPUART1_IRQHandler
	.thumb_set LPUART1_IRQHandler,Default_Handler

	.weak	LPTIM1_IRQHandler
	.thumb_set LPTIM1_IRQHandler,Default_Handler

	.weak	LPTIM2_IRQHandler
	.thumb_set LPTIM2_IRQHandler,Default_Handler

	.weak	TIM15_IRQHandler
	.thumb_set TIM15_IRQHandler,Default_Handler

	.weak	TIM16_IRQHandler
	.thumb_set TIM16_IRQHandler,Default_Handler

	.weak	TIM17_IRQHandler
	.thumb_set TIM17_IRQHandler,Default_Handler

	.weak	COMP_IRQHandler
	.thumb_set COMP_IRQHandler,Default_Handler

	.weak	USB_FS_IRQHandler
	.thumb_set USB_FS_IRQHandler,Default_Handler

	.weak	CRS_IRQHandler
	.thumb_set CRS_IRQHandler,Default_Handler

	.weak	OCTOSPI1_IRQHandler
	.thumb_set OCTOSPI1_IRQHandler,Default_Handler

	.weak	SDMMC1_IRQHandler
	.thumb_set SDMMC1_IRQHandler,Default_Handler

	.weak	GPDMA1_CHannel8_IRQHandler
	.thumb_set GPDMA1_CHannel8_IRQHandler,Default_Handler

	.weak	GPDMA1_CHannel9_IRQHandler
	.thumb_set GPDMA1_CHannel9_IRQHandler,Default_Handler

	.weak	GPDMA1_CHannel10_IRQHandler
	.thumb_set GPDMA1_CHannel10_IRQHandler,Default_Handler

	.weak	GPDMA1_CHannel11_IRQHandler
	.thumb_set GPDMA1_CHannel11_IRQHandler,Default_Handler

	.weak	I2C3_EV_IRQHandler
	.thumb_set I2C3_EV_IRQHandler,Default_Handler

	.weak	I2C3_ER_IRQHandler
	.thumb_set I2C3_ER_IRQHandler,Default_Handler

	.weak	SAI1_IRQHandler
	.thumb_set SAI1_IRQHandler,Default_Handler

	.weak	TSC_IRQHandler
	.thumb_set TSC_IRQHandler,Default_Handler

	.weak	AES_IRQHandler
	.thumb_set AES_IRQHandler,Default_Handler

	.weak	RNG_IRQHandler
	.thumb_set RNG_IRQHandler,Default_Handler

	.weak	FPU_IRQHandler
	.thumb_set FPU_IRQHandler,Default_Handler

	.weak	HASH_IRQHandler
	.thumb_set HASH_IRQHandler,Default_Handler

	.weak	PKA_IRQHandler
	.thumb_set PKA_IRQHandler,Default_Handler

	.weak	LPTIM3_IRQHandler
	.thumb_set LPTIM3_IRQHandler,Default_Handler

	.weak	SPI3_IRQHandler
	.thumb_set SPI3_IRQHandler,Default_Handler

	.weak	I3C2_ER_IRQHandler
	.thumb_set I3C2_ER_IRQHandler,Default_Handler

	.weak	I3C2_EV_IRQHandler
	.thumb_set I3C2_EV_IRQHandler,Default_Handler

	.weak	ICACHE_IRQHandler
	.thumb_set ICACHE_IRQHandler,Default_Handler

	.weak	LPTIM4_IRQHandler
	.thumb_set LPTIM4_IRQHandler,Default_Handler

	.weak	ADF1_IRQHandler
	.thumb_set ADF1_IRQHandler,Default_Handler

	.weak	ADC2_IRQHandler
	.thumb_set ADC2_IRQHandler,Default_Handler

	.weak	PWR_IRQHandler
	.thumb_set PWR_IRQHandler,Default_Handler

	.weak	PWR_S_IRQHandler
	.thumb_set PWR_S_IRQHandler,Default_Handler

	.weak	SystemInit

/************************ (C) COPYRIGHT STMicroelectonics *****END OF FILE****/
